defaults:
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - _self_

hydra:
  output_subdir: null
  run:
    dir: .

compute_landscape:
  data: "GB1"
  data_root_path: "/home/scratch/group_scratch/era/directed_evolution/data"
  device: "cuda:0"
  sampling_temperature: 1.0
  network_filename: "/home/scratch/group_scratch/era/directed_evolution/models/esm3clm/esm3_clm.pt"
  output_filename: "${compute_landscape.data}_all_energies_and_logps.hdf5"
  batch_size: 4
  gb1_muts_index: 100000
  model_config_filename: "/scratch/groups/rotskoff/sebastian/era/protein_era/cfgs/models/esm3_clm.yaml
