defaults:
  - nn: geometric_transformer
  - train: train
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - _self_

hydra:  
  output_subdir: null  
  run:  
    dir: .  

global_args:
  dataset_filename: "./alignment_dataset.hdf5"
  keys_to_test: ["nn.model", "nn.model_args"]